repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pdm run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: pdm run black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: pdm run pflake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: pdm run mypy
        require_serial: true
        language: system
        types: [python]
