name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Install dependencies
        run: pip install poetry~=1.1 'copier>=6.0.0a6'
      - name: Run test
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          copier -f -d docker=True -d docs=True . build/ && cd build/
          poetry run task lint
      - name: Push rendered project
        run: |
          REMOTE=https://${GITHUB_ACTOR}:${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git
          git -C build push -fu $REMOTE HEAD:rendered
